FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
ENV BASE_URL=/app/
RUN npm run build

# Stage 2 runtime
FROM nginx:alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html/app
COPY --from=builder /app/public/landing.html /usr/share/nginx/html/landing.html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]