server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Landing page
    location / {
        root /usr/share/nginx/html/landing;
        try_files /landing.html =404;
    }

    # React Spa at /app
    location ^~/app/ {
        root /usr/share/nginx/html/app;
        try_files $uri $uri/ /app/index.html =404;
    }

    location /api/ {
        proxy_pass http://api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}