apiVersion: v1
kind: Secret
metadata:
  name: task-tracker-secrets
  namespace: task-tracker
type: Opaque
stringData:
  PORT: "4000"
  NODE_ENV: "production"
  JWT_SECRET: "REPLACE_ME"
  MONGO_URI: "mongodb://mongo.task-tracker.svc.cluster.local:27017/project-task-tracker"
